Feature/chronic absenteeism update
edanalytics/edu_wh pull request #24
Opened 2023-01-19 00:45 UTC by ejoranlienea

This branch introduces two features and two potentially breaking changes to `fct_student_daily_attendance`:

1. **Make all indicators like `is_absent` floats instead of booleans**
  - This allows for fractional attendance codes (like half days), and makes it easier to sum indicators (without coercing them first)
  - Also makes it easier to introduce fully proportional daily attendance (computed from section attendance) without changing the table signature
  - **Migration:** `xwalk_attendance_events` must switch from `True/False` values in `is_absent` to numbers between 0 and 1. Existing T/F values can be swapped for `1.0` / `0.0`
  - **Migration:** Metrics should not coerce these indicators to integer to allow for fractional attendance

2. **Include daily attendance values for students after their enrollment ends.**
  - All indicators (absent, present, enrolled) are set to 0 after or between enrollments, so sums on these values still work as expected
  - This allows daily or over-time calculations of Chronic Absenteeism metrics, since these include students who were but are no longer enrolled. On days after or between enrollments, a student's absence rate, cumulative counts, and metric values stay as they were on their last enrolled day. If a student re-enrolls at the same school, counts continue accumulating after that day.
  - **Migration:** Average Daily Attendance style metrics should either filter out rows where `is_enrolled = 0` to avoid counting students not actually eligible, or make sure they are doing `sum(is_enrolled)` rather than `count(*)` to avoid inflating denominators.

Also introduces a configuration test to ensure all attendance codes are specified between 0 and 1, as setting a value like `50` instead of `0.5` would break the logic.

2023-01-25 20:43 UTC, rlittle08 requested changes

2023-01-25 20:43 UTC, rlittle08 commented on models/core_warehouse/fct_student_daily_attendance.sql
> +                when is_enrolled = 1 then fct_student_school_att.is_absent
should this be "not fct_student_school_att.is_absent"?

2023-01-25 20:43 UTC, rlittle08 commented on models/core_warehouse/fct_student_daily_attendance.sql
> +        sum(is_enrolled) over(
there's now no difference between total_days_enrolled and cumulative_days_enrolled, so do we need both columns?

2023-01-27 22:50 UTC, ejoranlienea commented on models/core_warehouse/fct_student_daily_attendance.sql
> +                when is_enrolled = 1 then fct_student_school_att.is_absent
No -- since `is_absent` is no longer boolean, we have to do this `1 - is_absent` math.
Basically: if `is_absent` = 1, then 1-1 = 0
`is_absent` = 0, then 1-0 = 1
`is_absent` = 0.5, then 1-0.5 = 0.5

2023-01-27 22:51 UTC, ejoranlienea commented on models/core_warehouse/fct_student_daily_attendance.sql
> +        sum(is_enrolled) over(
They're still different -- cumulative counts up throughout the year, while total is always the final total. Either can be useful for inclusion business rules.

2023-01-27 22:54 UTC, ejoranlienea commented
A couple new changes:
- Exclude rows from the enrollment table where `exit_withdraw_date` is either before the first day of school, or before the students reported `entry_date` -- consider these invalid enrollment records.
- Add an audit table that captures all dropped enrollment records for inspection if necessary.

2023-02-07 20:54 UTC, merged