Feature/optional program associations
edanalytics/edu_wh pull request #35
Opened 2023-02-13 21:30 UTC by jayckaiser

This branch standardizes and renames all program association build models such that they are structured identically. This branch and [feature/standardize_program_associations in edu_edfi_source](https://github.com/edanalytics/edu_edfi_source/pull/20) are co-dependent and must be merged together.

This branch changes the column names of program start and end dates in particular, so this will break existing Stadium implementations that define 'edu:special_ed:start_date_column' as "spec_ed_program_begin_date" (as well as the end-date column).

Both branches will require thorough code review to verify they are feature-complete. Both have been tested successfully against Stadium South Carolina.

2023-02-17 19:48 UTC, rlittle08 requested changes

2023-02-17 19:48 UTC, rlittle08 commented on models/core_warehouse/dim_student.sql
> +            {% if 'annual' in var('edu:special_ed:agg_types') %}
could this be a for loop over program types?

2023-02-17 19:48 UTC, rlittle08 commented on models/core_warehouse/fct_student_special_education_program_association.sql
> +        "alter table {{ this }} add primary key (k_student, k_student_xyear, k_program, k_school, program_enroll_begin_date)",
k_school isn't needed in pkey, it's part of k_program

2023-02-17 19:48 UTC, rlittle08 commented on macros/any_var.sql
> +{% macro any_var(var_list, default=True) %}
where is this macro used?

2023-02-23 20:05 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
I agree with this, and I'll look for a solution that does not require this function explicitly.

2023-02-23 20:07 UTC, jayckaiser commented on macros/any_var.sql
> +{% macro any_var(var_list, default=True) %}
This macro is not used currently. The hope was to use it in the properties config yaml for `fct_student_programs`, but the enabled field cannot be populated by a macro. I still wonder if there's a workaround that will use the macro, so I haven't removed it yet.

2023-02-23 20:08 UTC, jayckaiser commented on models/core_warehouse/dim_student.sql
> +            {% if 'annual' in var('edu:special_ed:agg_types') %}
Yes this can, and that's a good idea that I'll implement.

2023-02-23 20:08 UTC, jayckaiser commented on models/core_warehouse/fct_student_special_education_program_association.sql
> +        "alter table {{ this }} add primary key (k_student, k_student_xyear, k_program, k_school, program_enroll_begin_date)",
Understood, and will be removed!

2023-02-23 23:43 UTC, susanxiong commented
@jayckaiser  Jeffco is going to be using this! Do you need any support for testing it out? Could @sleblanc23 and I pull it and test it out in jeffco dev (i.e. is it ready for that)?

2023-02-23 23:45 UTC, susanxiong commented on models/build/edfi_3/students/bld_ef3__student_program__special_education.sql
> +{# customizable: certain program names may be excluded and not counted as language instruction #}
typo: should read "customizable: certain program names may be excluded and not counted as special education"

2023-02-24 15:25 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__special_education.sql
> +{# customizable: certain program names may be excluded and not counted as language instruction #}
Good catch!

2023-02-24 15:34 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
That looks good, @rlittle08. However, I wonder if it can be simplified. Could a `max()` be used cross-platform instead?
https://stackoverflow.com/a/58620918

2023-02-24 15:38 UTC, rlittle08 commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
as in, don't use the boolor_agg function for snowflake, use max for all?

also do you mean max without casting to int?

2023-02-24 15:58 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
I wonder whether we could just use `max()` for all platforms, ignoring `boolor_agg()` altogether. There may be performance-differences between the two methods, but given the data-size, I don't expect these to be limiting.

I also don't believe we will need a cast to int. Maybe this won't be the case in other platforms, but min/max logic should be identical whether working with booleans or numerics.

2023-02-27 17:06 UTC, rlittle08 commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
you can't `max()` booleans in Postgres :(

2023-02-27 17:44 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
Ah darn. So there's a decision to be made here, depending on the depth to which we want to build cross-platform variability in our code.

Option 1: `max(is_homeless_annual::integer)::boolean`
Option 2: `{{ boolor_agg('is_homeless_annual') }}`

I don't think it likely that a `boolor_agg()` function will be used in too many places, so I'd consider whether it's worth keeping at all in favor for generic and built-in methods, even if they're slightly less performant or unsightly.

2023-03-01 23:18 UTC, jayckaiser commented on models/build/edfi_3/students/bld_ef3__student_program__homeless.sql
> +        boolor_agg(is_homeless_annual) as is_homeless_ever
I've chatted with Erik. When we get into cross-database support, we can revisit how this method is implemented. For now though, in Snowflake, this max will work fine.

2023-03-02 23:23 UTC, ejoranlienea approved these changes

2023-03-02 23:24 UTC, merged