Build/Learning standards Models
edanalytics/edu_wh pull request #76
Opened 2023-10-09 16:04 UTC by AngelicaLastra

## Description & motivation
This PR is linked to [edu_edfi_source PR #43](https://github.com/edanalytics/edu_edfi_source/pull/43) and  creates models for learning standard data to be used downstream by student grade tables.

## PR Merge Priority:

- [x] Low
- [ ] Medium
- [ ] High

## New files created:
- `dim_learning_standards.sql` : This table contains attributes and descriptors for unique Learning Standards.
- `fct_student_learning_standard_grades.sql` : This fact table contains student learning standard grades by grading period within the school year. There is one record per student, school, course section, grading period, and learning standard.
- `fct_student_learning_standard_grades.yml` and `dim_learning_standards.yml` : Description for models and columns created.

## Tests and QC done:
- Executed a successful dbt run.
- Queried both Boston and Jeffco data warehouses to ensure data was accurately populated in the tables.
- Validated the granularity of the tables by querying each learning standard ID in the learning standard tables and cross-referencing it with a student, course section, school, grading period, and learning standard in the student learning standard grades table.
- Counted rows throughout to ensure there was no fan out of data, and queried distinct values to ensure data was represented properly.

## Future ToDos & Questions: 
(based on [edu_edfi_source PR #43](https://github.com/edanalytics/edu_edfi_source/pull/43))
- There is a question about the grade range a student can earn through a learning standard (what is the max? the min?). We have not yet been able to come to a solution for this since this data doesn't seem to be coming through from the learning standard source (there is an ongoing conversation between Jordan, Rob, and me about this).
- Academic subject values can sometimes appear cryptic (ex: F1FC8A52-3B53-11E0-B042-495E9DFF4B22 ) however, in other instances, the naming convention is more conventional, such as "Science." We should consider if there's a way to transform them into more readable subject names or if they are helpful as is.
- Some learning_standard_id values have some helpful descriptions (ex: Math-Effort_rbcX200MATH00000010001111000) while some are less helpful (ex: c86bc12e-e6e3-467b-b8a8-bacc46c95b37) for now we don't do anything with this column but it is something to consider for the future.

2023-10-12 18:39 UTC, rlittle08 requested changes

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.sql
> +        stg_learning_standards.v_ext
we don't pull `v_ext` into warehouse tables. the general strategy is to pull any info from `v_ext` out into their own columns using config at the stg models. Or in rare cases, warehouse models might use `extract_extension` directly to again pull extended columns from config, as is done [here ](https://github.com/edanalytics/edu_wh/blob/322e27db246a9278047aa43198037635fe7c263b/models/core_warehouse/fct_student_program_association.sql#L43)

It's possible we should add that `extract_extension` code to more warehouse models, like this one, but we haven't had many uses for that, yet.

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.sql
> +        stg_learning_standards.parent_learning_standard_reference,
erik's latest branch creates a surrogate key for this, which we should use instead -- `k_learning_standard__parent`.

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.sql
> +        stg_learning_standards.v_learning_standard_identification_codes,
consider reordering columns to have all `v_` columns grouped at or toward the end

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +    join dim_learning_standards
in erik's branch, `k_learning_standard` is not generated in the student table using a reference to `gen_skey`. so this join can be on just `k_learning_standard`.

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +        dim_learning_standards.v_academic_subjects,
I think best to keep `v_academic_subjects` only within the dim

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +        stg_grades_learning_standards.performance_base_conversion_descriptor as performance_base_conversion,
in erik's branch, this is now extracted in base

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +        dim_learning_standards.k_learning_standard,
can you move `grade_type` in front of `k_learning_standard`, to match the order of `fct_student_grades` and make clear that `grade_type` is part of the unique key?

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.yml
> +        Defines individial attributes of a learning standard, who maintains them, when they were created, academic subjects related,
nice description and documentation of columns

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
nice addition

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
maybe also note that this model has a similar natural key to fct_student_grades, and that they're sourced from the same Ed-Fi Resource?

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +      - name: v_academic_subjects
remember to remove this if we remove from fct table

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
consider adding an example query, either for general use, or one that would be uniquely useful to boston or jeff co (I can show you how we do implementation-specific examples in docs)

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.yml
> +      - name: learning_standard_scope_descriptor
remember to change, these have been extracted in the base model now

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.sql
> +        stg_learning_standards.v_learning_standard_category_descriptor,
erik's latest branch extracts these in the base model

2023-10-12 18:39 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.yml
> +          A coding scheme that is used for identification and record-keeping purposes by schools,
for list columns, maybe mention that they are lists

2023-10-16 22:03 UTC, AngelicaLastra commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +        stg_grades_learning_standards.performance_base_conversion_descriptor as performance_base_conversion,
I made a change where I kept the name "stg_grades_learning_standards.performance_base_conversion_descriptor" (based on Erik's models) instead of renaming the column to "performannce_base_conversion" as I had done originally. We should probably not rename this column at this level in the warehouse and instead do so at the staging/base level but let me know if this doesn't sound right to you!

2023-10-30 18:17 UTC, AngelicaLastra commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
I added the config file, not sure what query we would want to include since learning standards is a pretty straightforward model, but I added some in the custom doc in [Stadium_Boston](https://github.com/edanalytics/stadium_boston/compare/main...docs/custom_doc_fct_student_learning_standard_grades#diff-56dc44becc0af893ec36929c32f29cc281891ce228b1552d7899392b53785790R140-R173)

2023-10-30 18:24 UTC, AngelicaLastra commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
I think the problem I am having is that this ^ is not stadium boston specific, so I am thinking I will add it hardcoded here instead.

2023-10-30 20:04 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
agreed, i think this is a good generic example!

2023-10-30 20:18 UTC, rlittle08 requested changes

2023-10-30 20:18 UTC, rlittle08 commented on models/core_warehouse/dim_learning_standards.sql
can you rename to `dim_learning_standard` to match the singular format of other dims e.g. dim_school, etc.

2023-10-30 20:18 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.sql
> +        "alter table {{ this }} add constraint fk_{{ this.name }}_course_section foreign key (k_course_section) references {{ ref('dim_course_section') }}",
i think missing a fk to dim_learning_standard

2023-10-30 20:18 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
are there any other examples that are more boston-specific and analytical in nature? I know they were interested in IB grades, is it possible to write a query that subsets to only IB learning standard grades for Boston's dbt docs?

2023-10-30 20:18 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +          Unique identifier for a learning standard. Foreign key reference to [dim_learning_standards](#!/model/model.edu_wh.dim_learning_standards).
change link here if rename to `dim_learning_standard` (singular)

2023-10-30 20:18 UTC, rlittle08 commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +            - k_course_section
missing grade_type

2023-10-30 21:36 UTC, AngelicaLastra commented on models/core_warehouse/fct_student_learning_standard_grades.yml
> +        Note that `k_learning_standard` is part of the Primary Key, meaning a student
Yes! You are right, that would be a good one to include! [Boston Stadium Custom Doc PR](https://github.com/edanalytics/stadium_boston/pull/55#issue-1969264675).

2023-11-21 21:13 UTC, rlittle08 approved these changes

2023-11-29 00:56 UTC, merged