Feature/optional filter early exits
edanalytics/edu_wh pull request #79
Opened 2023-10-30 16:20 UTC by rlittle08

## Description & motivation
Make optional an existing rule to stu-school-association: excluding students who exited before the first day of school. This rule exists to avoid carrying around student records that aren't relevant for analysis, but in certain cases, these students _are_ needed for analysis, e.g. dropout analysis. 

This PR is non-breaking, non-changing by default, but if implementations add variable config:
```
'edu:enroll:exclude_exit_before_first_day': False
```
, then early-exit students will be included in the warehouse on future dbt runs.

## PR Merge Priority:

- [x] Low
- [ ] Medium
- [ ] High

## Changes to existing files:

- `fct_student_school_association`: add conditional block around existing exclusion code

## New files created:

None

## Tests and QC done:

Tested on Boston with empty, False, and True config

- Should early exit students be tracked in a separate table?

2023-11-01 22:13 UTC, ejoranlienea requested changes

2023-11-01 22:13 UTC, ejoranlienea commented on models/core_warehouse/fct_student_school_association.sql
> +   {% set excl_early_exit =  var('edu:enroll:exclude_exit_before_first_day', True)  %}
Is this `set` necessary, or can it just be `if var(...)`?

2023-11-03 18:13 UTC, rlittle08 commented on models/core_warehouse/fct_student_school_association.sql
> +   {% set excl_early_exit =  var('edu:enroll:exclude_exit_before_first_day', True)  %}
done & tested

2023-11-08 19:30 UTC, ejoranlienea approved these changes

2023-11-08 19:30 UTC, merged