Student academic records - add k_student_xyear
edanalytics/edu_wh pull request #95
Opened 2023-12-11 19:53 UTC by sleblanc23

## Description & motivation

## Changes to existing files:
- `fct_course_transcripts` : 
- `fct_student_academic_record` : 
- `fct_student_gpa` : 

## Tests and QC done (together with ):
- Confirmed that row counts were unchanged in Jeffco
- Confirmed that `most_recent_k_student` logic is working

## PR Merge Priority:
Low - note this depends on

2023-12-14 22:32 UTC, rlittle08 requested changes

2023-12-14 22:32 UTC, rlittle08 commented on models/core_warehouse/fct_course_transcripts.yml
> +        ```
Should we add a 2nd example query with join on `k_student`, and explain that you can use that to get students' demographics from latest year? Or do we want to discourage that behavior?

2023-12-14 22:32 UTC, rlittle08 commented on models/core_warehouse/fct_student_academic_record.yml
> +    description: >
thank you for adding docs!

2023-12-14 22:32 UTC, rlittle08 commented on models/core_warehouse/fct_student_gpa.yml
> +    columns:
can you please add column descriptions for gpa_type -> max_gpa_value?

2023-12-18 17:23 UTC, sleblanc23 commented on models/core_warehouse/fct_course_transcripts.yml
> +        ```
Yeah, I think that's worth doing. If nothing else it reinforces that there are multiple options that need to be considered here

2023-12-18 17:55 UTC, sleblanc23 commented on models/core_warehouse/fct_student_gpa.sql
> +most_recent_k_student as (
I think that's a good idea. It's also used in fct_student_parent_association, so I think that's enough use cases to add a build model for it.

I added this model and references to it. I also included `api_year` in the build model, though it's not used yet. I thought someone might want to easily reference which year of data is the most recent.

2023-12-21 00:17 UTC, sleblanc23 commented
@ejoranlienea I added k_student in the warehouse models by joining to `dim_student` on `k_student_xyear` and `school_year` rather than modifying our `gen_skey` macro. I know that goes against our typical pattern of doing all keying in stage. Do you have an opinion one way or the other?

2024-01-24 19:46 UTC, ejoranlienea approved these changes

2024-01-24 19:47 UTC, ejoranlienea approved these changes

2024-01-24 19:47 UTC, rlittle08 approved these changes

2024-01-24 19:47 UTC, merged