docs/fct_student_assessment
edanalytics/edu_wh pull request #96
Opened 2023-12-13 19:42 UTC by sleblanc23

Added a sample query for unpacking a particular score result from `fct_student_assessment.v_other_results`. Denver is interested in several of these score results for their reporting and I thought it was worth adding the sample here rather than in a Denver custom doc.

2023-12-14 22:21 UTC, rlittle08 requested changes

2023-12-14 22:21 UTC, rlittle08 commented on models/core_warehouse/fct_student_assessment.yml
> +      ##### Example of querying "other results":
very picky but can we use the ```##### Example Use Cases:``` header instead, to be consistent with other docs pages?

2023-12-18 16:55 UTC, sleblanc23 commented on models/core_warehouse/fct_student_assessment.yml
> +      ##### Example of querying "other results":
fixed!

2023-12-18 17:13 UTC, rlittle08 approved these changes

2023-12-19 00:24 UTC, jalvord1 commented on models/core_warehouse/fct_student_assessment.yml
> +      Any score that are not included in the wide score results columns are listed in the `v_other_results` column. They can be included
this is tiny, can we change to 'Any scores' or 'Any score that is'?

2023-12-19 14:49 UTC, sleblanc23 commented on models/core_warehouse/fct_student_assessment.yml
> +      Any score that are not included in the wide score results columns are listed in the `v_other_results` column. They can be included
oops. fixed!

2023-12-19 14:50 UTC, jalvord1 approved these changes

2023-12-21 00:35 UTC, ejoranlienea approved these changes

2023-12-21 00:35 UTC, merged